spring.application.name=USER-SERVICE

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#server.servlet.context-path=/springprojecteclipse

#port can be changed if required
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.security.user.name = tester
spring.security.user.password = dev@123
#server.servlet.session.cookie.same-site=strict

spring.datasource.url=jdbc:postgresql://localhost:5432/devserver
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=dev@123


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
